services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image-converter
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    expose:
      - 9000
      - 9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
        required: true
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/image-converter;
      /usr/bin/mc mb myminio/image-converter;
      exit 0;
      "
  image-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Database=image-converter;Username=postgres;Password=postgres
      - S3__AccessKey=minioadmin
      - S3__SecretKey=minioadmin
      - S3__ServiceUrl=http://minio:9000
      - S3__BucketName=image-converter
    depends_on:
      - postgres
      - minio
      - createbuckets
  
volumes:
  minio-data: